name: Count Packages

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  badge_job:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: count
        run: echo "PKG_COUNT=$(find pkg/* -maxdepth 0 -type d | wc -l)" >> $GITHUB_ENV
      - name: count badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: count
          LABEL: 'Packages'
          STATUS: ${{ env.PKG_COUNT }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
